//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaKomputerowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drukarki
    {
        public int DrukarkiID { get; set; }
        public int SN { get; set; }
        public string Format_papieru { get; set; }
        public bool Kolor { get; set; }
        public string Typ_Drukarki { get; set; }
        public double Cena { get; set; }
    
        public virtual Produkty Produkty { get; set; }
    }
}
